### ISSUE TITLE
404 on coc link

### ISSUE THREAD

**Issue by aretecode** [lodash/lodash-doc-globals#4]
https://github.com/lodash/lodash-doc-globals/blob/master/.github/CONTRIBUTING.md#contributing-to-lodash-doc-globals
https://js.foundation/conduct/ 
<img width="885" alt="screen shot 2017-06-25 at 2 56 13 am" src="https://user-images.githubusercontent.com/4022631/27515136-e0a59d34-5951-11e7-9ddf-e7bf2ba64a3c.png">

**Comment by kborchers** [comment]
Thank you for reporting. This issue has been corrected.
